# Generated by Django 3.0.4 on 2020-06-12 14:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sharps', django_mysql.models.ListCharField(models.IntegerField(default=0), max_length=100, size=20)),
                ('site', models.CharField(blank=True, max_length=10)),
                ('p_TNM', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
