# Generated by Django 3.0.4 on 2020-06-12 16:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('CaneXapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('vectors', django_mysql.models.ListCharField(models.IntegerField(default=0), max_length=5000, size=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sharps',
        ),
    ]
