# Generated by Django 3.0.4 on 2020-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaneXapp', '0003_auto_20200612_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharp',
            name='vectors',
            field=models.TextField(),
        ),
    ]
