# Generated by Django 3.0.4 on 2020-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaneXapp', '0004_auto_20200613_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
